import Head from "next/head";

// Components
import { Header, HeroSection, ProjectsSection } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <HeroSection />
        <ProjectsSection />
      </main>
    </>
  );
}
